name: widgets
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.9
  transparent_image: ^2.0.0
  cached_network_image: ^3.0.0
  extended_image: ^3.0.0
  new_gradient_app_bar: ^0.2.0
  badges: ^2.0.3
  flutter_slidable: ^1.3.0
  backdrop: ^0.6.0
  convex_bottom_bar: ^3.0.0
  hidable: ^1.0.2
  intl: ^0.17.0
  english_words: ^4.0.0
  animations: ^2.0.0
  animated_radial_menu: ^0.0.1
  lottie: ^1.0.0
  animated_text_kit: ^4.0.0
  image_picker: ^0.7.0
  video_player: ^2.4.5
  shared_preferences: ^2.0.15

#  passwordfield: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/lotties/
    - assets/video/
